source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.3'

gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.7', '>= 6.1.7.2'
gem 'sass-rails', '>= 6'

# Administration
gem 'activeadmin'
gem 'activeadmin_addons'
gem 'coffee-rails', '~> 5.0.0'
gem 'devise'

# Queue broker
gem 'karafka', '~> 2.0'

gem "tzinfo-data"

group :development, :test do
  gem 'byebug'
  gem 'rubocop', require: false
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end

group :development do
  gem 'annotate', require: false
  gem 'better_errors'
  gem 'listen', '~> 3.3'
  gem 'web-console', '>= 4.1.0'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver', '>= 4.0.0.rc1'
  gem 'webdrivers'
end
